\set ON_ERROR_STOP on
SET client_encoding = 'UTF8';

BEGIN;

CREATE TABLE IF NOT EXISTS pk_users (
    user_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login text NOT NULL UNIQUE,
    full_name text NOT NULL,
    password_hash text NOT NULL,
    must_change_password integer NOT NULL DEFAULT 1,
    is_active integer NOT NULL DEFAULT 1,
    failed_login_count integer NOT NULL DEFAULT 0,
    locked_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz,
    CONSTRAINT ck_pk_users_must_change
        CHECK (must_change_password IN (0, 1)),
    CONSTRAINT ck_pk_users_active CHECK (is_active IN (0, 1)),
    CONSTRAINT ck_pk_users_failed_login CHECK (failed_login_count >= 0)
);

CREATE TABLE IF NOT EXISTS pk_roles (
    role_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code text NOT NULL UNIQUE,
    name text NOT NULL
);

CREATE TABLE IF NOT EXISTS pk_user_roles (
    user_id bigint NOT NULL,
    role_id bigint NOT NULL,
    PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_pk_user_roles_user
        FOREIGN KEY (user_id) REFERENCES pk_users(user_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_pk_user_roles_role
        FOREIGN KEY (role_id) REFERENCES pk_roles(role_id)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS pk_user_units (
    user_id bigint NOT NULL,
    jo_id text NOT NULL,
    jo_symbol text,
    jo_nazwa text,
    is_default integer NOT NULL DEFAULT 0,
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id, jo_id),
    CONSTRAINT fk_pk_user_units_user
        FOREIGN KEY (user_id) REFERENCES pk_users(user_id)
        ON DELETE CASCADE,
    CONSTRAINT ck_pk_user_units_default CHECK (is_default IN (0, 1))
);

CREATE TABLE IF NOT EXISTS pk_programy (
    program_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kod text NOT NULL UNIQUE,
    nazwa text NOT NULL,
    wersja text,
    opis text,
    czy_aktywny integer NOT NULL DEFAULT 1,
    data_od date,
    data_do date,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz,
    CONSTRAINT ck_pk_programy_active CHECK (czy_aktywny IN (0, 1))
);

CREATE TABLE IF NOT EXISTS pk_program_units (
    program_id bigint NOT NULL,
    jo_id text NOT NULL,
    jo_symbol text,
    jo_nazwa text,
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (program_id, jo_id),
    CONSTRAINT fk_pk_program_units_program
        FOREIGN KEY (program_id) REFERENCES pk_programy(program_id)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS pk_sciezki (
    sciezka_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    program_id bigint NOT NULL,
    kod text NOT NULL,
    nazwa text NOT NULL,
    opis text,
    czy_aktywna integer NOT NULL DEFAULT 1,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz,
    CONSTRAINT uq_pk_sciezki_program_kod UNIQUE (program_id, kod),
    CONSTRAINT fk_pk_sciezki_program
        FOREIGN KEY (program_id) REFERENCES pk_programy(program_id),
    CONSTRAINT ck_pk_sciezki_active CHECK (czy_aktywna IN (0, 1))
);

CREATE TABLE IF NOT EXISTS pk_pathway_units (
    sciezka_id bigint NOT NULL,
    jo_id text NOT NULL,
    jo_symbol text,
    jo_nazwa text,
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (sciezka_id, jo_id),
    CONSTRAINT fk_pk_pathway_units_pathway
        FOREIGN KEY (sciezka_id) REFERENCES pk_sciezki(sciezka_id)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS pk_typy_elementow (
    typ_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kod text NOT NULL UNIQUE,
    nazwa text NOT NULL,
    opis text,
    kolejnosc integer NOT NULL DEFAULT 0,
    czy_aktywny integer NOT NULL DEFAULT 1,
    czy_systemowy integer NOT NULL DEFAULT 0,
    ikona text,
    kolor text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz,
    CONSTRAINT ck_pk_typy_elementow_active
        CHECK (czy_aktywny IN (0, 1)),
    CONSTRAINT ck_pk_typy_elementow_system
        CHECK (czy_systemowy IN (0, 1)),
    CONSTRAINT ck_pk_typy_elementow_order
        CHECK (kolejnosc >= 0)
);

CREATE TABLE IF NOT EXISTS pk_jednostki_czasu (
    jednostka_czasu_id bigint
        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kod text NOT NULL UNIQUE,
    nazwa text NOT NULL,
    opis text,
    rodzaj_obliczenia text NOT NULL,
    mnoznik integer NOT NULL DEFAULT 1,
    kolejnosc integer NOT NULL DEFAULT 0,
    czy_aktywny integer NOT NULL DEFAULT 1,
    czy_systemowy integer NOT NULL DEFAULT 0,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz,
    CONSTRAINT ck_pk_jednostki_czasu_calculation
        CHECK (rodzaj_obliczenia IN ('DNI', 'MIESIACE', 'LATA')),
    CONSTRAINT ck_pk_jednostki_czasu_multiplier CHECK (mnoznik > 0),
    CONSTRAINT ck_pk_jednostki_czasu_order CHECK (kolejnosc >= 0),
    CONSTRAINT ck_pk_jednostki_czasu_active
        CHECK (czy_aktywny IN (0, 1)),
    CONSTRAINT ck_pk_jednostki_czasu_system
        CHECK (czy_systemowy IN (0, 1))
);

CREATE TABLE IF NOT EXISTS pk_klocki (
    klocek_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kod text NOT NULL UNIQUE,
    nazwa text NOT NULL,
    opis text,
    typ_elementu_id bigint NOT NULL,
    ikona text,
    kolor text NOT NULL DEFAULT '#828282',
    kolor_tekstu text NOT NULL DEFAULT '#FFFFFF',
    domyslny_termin_liczba integer,
    domyslna_jednostka_czasu_id bigint,
    czy_wymaga_zlecenia integer NOT NULL DEFAULT 0,
    czy_obowiazkowy integer NOT NULL DEFAULT 0,
    czy_aktywny integer NOT NULL DEFAULT 1,
    czy_systemowy integer NOT NULL DEFAULT 0,
    kolejnosc integer NOT NULL DEFAULT 0,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz,
    CONSTRAINT fk_pk_klocki_type
        FOREIGN KEY (typ_elementu_id)
        REFERENCES pk_typy_elementow(typ_id),
    CONSTRAINT fk_pk_klocki_time_unit
        FOREIGN KEY (domyslna_jednostka_czasu_id)
        REFERENCES pk_jednostki_czasu(jednostka_czasu_id),
    CONSTRAINT ck_pk_klocki_deadline
        CHECK (
            domyslny_termin_liczba IS NULL
            OR domyslny_termin_liczba >= 0
        ),
    CONSTRAINT ck_pk_klocki_deadline_pair
        CHECK (
            (
                domyslny_termin_liczba IS NULL
                AND domyslna_jednostka_czasu_id IS NULL
            )
            OR
            (
                domyslny_termin_liczba IS NOT NULL
                AND domyslna_jednostka_czasu_id IS NOT NULL
            )
        ),
    CONSTRAINT ck_pk_klocki_order_required
        CHECK (czy_wymaga_zlecenia IN (0, 1)),
    CONSTRAINT ck_pk_klocki_required
        CHECK (czy_obowiazkowy IN (0, 1)),
    CONSTRAINT ck_pk_klocki_active CHECK (czy_aktywny IN (0, 1)),
    CONSTRAINT ck_pk_klocki_system CHECK (czy_systemowy IN (0, 1)),
    CONSTRAINT ck_pk_klocki_order CHECK (kolejnosc >= 0),
    CONSTRAINT ck_pk_klocki_color
        CHECK (kolor ~ '^#[0-9A-Fa-f]{6}$'),
    CONSTRAINT ck_pk_klocki_text_color
        CHECK (kolor_tekstu ~ '^#[0-9A-Fa-f]{6}$')
);

CREATE TABLE IF NOT EXISTS pk_rodzaje_wizyt_eskulap (
    rodzaj_wizyty_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parametr_kod text NOT NULL UNIQUE,
    parametr_nazwa text NOT NULL,
    czy_aktualny_eskulap integer NOT NULL DEFAULT 1,
    czy_aktywny_kompas integer NOT NULL DEFAULT 1,
    first_seen_at timestamptz NOT NULL DEFAULT now(),
    last_seen_at timestamptz,
    synchronized_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz,
    CONSTRAINT ck_pk_rodzaje_wizyt_eskulap_current
        CHECK (czy_aktualny_eskulap IN (0, 1)),
    CONSTRAINT ck_pk_rodzaje_wizyt_eskulap_active
        CHECK (czy_aktywny_kompas IN (0, 1)),
    CONSTRAINT ck_pk_rodzaje_wizyt_eskulap_code
        CHECK (length(trim(parametr_kod)) > 0),
    CONSTRAINT ck_pk_rodzaje_wizyt_eskulap_name
        CHECK (length(trim(parametr_nazwa)) > 0)
);

CREATE TABLE IF NOT EXISTS pk_mapowanie_wizyt (
    mapowanie_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    klocek_id bigint NOT NULL,
    rodzaj_wizyty_id bigint NOT NULL,
    czy_aktywne integer NOT NULL DEFAULT 1,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz,
    CONSTRAINT fk_pk_mapowanie_wizyt_klocek
        FOREIGN KEY (klocek_id)
        REFERENCES pk_klocki(klocek_id),
    CONSTRAINT fk_pk_mapowanie_wizyt_rodzaj
        FOREIGN KEY (rodzaj_wizyty_id)
        REFERENCES pk_rodzaje_wizyt_eskulap(rodzaj_wizyty_id),
    CONSTRAINT uq_pk_mapowanie_wizyt_klocek_rodzaj
        UNIQUE (klocek_id, rodzaj_wizyty_id),
    CONSTRAINT ck_pk_mapowanie_wizyt_active
        CHECK (czy_aktywne IN (0, 1))
);

CREATE TABLE IF NOT EXISTS pk_sciezka_elementy (
    element_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sciezka_id bigint NOT NULL,
    klocek_id bigint NOT NULL,
    lp integer NOT NULL,
    nazwa_w_sciezce text NOT NULL,
    min_liczba integer DEFAULT 0,
    max_liczba integer,
    czy_obowiazkowy integer NOT NULL DEFAULT 0,
    czy_wymaga_zlecenia integer NOT NULL DEFAULT 0,
    termin_liczba integer,
    termin_jednostka text,
    termin_od text,
    warunek_aktywacji text,
    opis_organizacyjny text,
    czy_aktywny integer NOT NULL DEFAULT 1,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz,
    CONSTRAINT uq_pk_sciezka_elementy_lp UNIQUE (sciezka_id, lp),
    CONSTRAINT fk_pk_sciezka_elementy_pathway
        FOREIGN KEY (sciezka_id) REFERENCES pk_sciezki(sciezka_id),
    CONSTRAINT fk_pk_sciezka_elementy_block
        FOREIGN KEY (klocek_id) REFERENCES pk_klocki(klocek_id),
    CONSTRAINT ck_pk_sciezka_elementy_required
        CHECK (czy_obowiazkowy IN (0, 1)),
    CONSTRAINT ck_pk_sciezka_elementy_order
        CHECK (czy_wymaga_zlecenia IN (0, 1)),
    CONSTRAINT ck_pk_sciezka_elementy_active
        CHECK (czy_aktywny IN (0, 1)),
    CONSTRAINT ck_pk_sciezka_elementy_counts
        CHECK (
            min_liczba IS NULL
            OR max_liczba IS NULL
            OR min_liczba <= max_liczba
        )
);

CREATE TABLE IF NOT EXISTS pk_sciezka_zaleznosci (
    zaleznosc_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sciezka_id bigint NOT NULL,
    element_od_id bigint NOT NULL,
    element_do_id bigint NOT NULL,
    typ text NOT NULL,
    opis text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz,
    CONSTRAINT uq_pk_sciezka_zaleznosci
        UNIQUE (sciezka_id, element_od_id, element_do_id),
    CONSTRAINT fk_pk_sciezka_zaleznosci_pathway
        FOREIGN KEY (sciezka_id) REFERENCES pk_sciezki(sciezka_id),
    CONSTRAINT fk_pk_sciezka_zaleznosci_from
        FOREIGN KEY (element_od_id)
        REFERENCES pk_sciezka_elementy(element_id),
    CONSTRAINT fk_pk_sciezka_zaleznosci_to
        FOREIGN KEY (element_do_id)
        REFERENCES pk_sciezka_elementy(element_id),
    CONSTRAINT ck_pk_sciezka_zaleznosci_type
        CHECK (typ IN ('KOLEJNOSC', 'WARUNEK')),
    CONSTRAINT ck_pk_sciezka_zaleznosci_self
        CHECK (element_od_id <> element_do_id)
);

CREATE TABLE IF NOT EXISTS pk_wyzwalacze (
    trigger_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    element_id bigint NOT NULL,
    trigger_type text NOT NULL,
    trigger_element_id bigint,
    opis text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz,
    CONSTRAINT fk_pk_wyzwalacze_element
        FOREIGN KEY (element_id) REFERENCES pk_sciezka_elementy(element_id),
    CONSTRAINT fk_pk_wyzwalacze_source
        FOREIGN KEY (trigger_element_id)
        REFERENCES pk_sciezka_elementy(element_id),
    CONSTRAINT ck_pk_wyzwalacze_type CHECK (
        trigger_type IN (
            'START_EPIZODU',
            'PO_ZAKONCZENIU',
            'PO_ZLECENIU',
            'PO_WYNIKU',
            'RECZNIE'
        )
    )
);

-- Epizod przechowuje wyłącznie techniczny identyfikator z Eskulapa.
-- Dane osobowe pacjenta są pobierane na żądanie przez Eskulap Gateway.
CREATE TABLE IF NOT EXISTS pk_epizody (
    epizod_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pacjent_id_eskulap text NOT NULL,
    program_id bigint,
    sciezka_id bigint,
    data_start date,
    data_zakonczenia date,
    status text NOT NULL DEFAULT 'NOWY',
    koordynator_id text,
    uwagi text,
    source_system text,
    source_type text,
    source_id text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz,
    CONSTRAINT fk_pk_epizody_program
        FOREIGN KEY (program_id) REFERENCES pk_programy(program_id),
    CONSTRAINT fk_pk_epizody_pathway
        FOREIGN KEY (sciezka_id) REFERENCES pk_sciezki(sciezka_id)
);

CREATE TABLE IF NOT EXISTS pk_epizod_elementy (
    epizod_element_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    epizod_id bigint NOT NULL,
    sciezka_element_id bigint,
    klocek_id bigint NOT NULL,
    element_zrodlowy_id bigint,
    nazwa text NOT NULL,
    lp integer NOT NULL,
    min_liczba integer DEFAULT 0,
    max_liczba integer,
    termin_liczba integer,
    jednostka_czasu_id bigint,
    termin_od_epizod_element_id bigint,
    czy_wymagany integer NOT NULL DEFAULT 0,
    czy_wymaga_zlecenia integer NOT NULL DEFAULT 0,
    czy_aktywny integer NOT NULL DEFAULT 1,
    typ_pochodzenia text NOT NULL DEFAULT 'SCIEZKA',
    powod_modyfikacji text,
    created_at timestamptz NOT NULL DEFAULT now(),
    created_by text,
    updated_at timestamptz,
    updated_by text,
    CONSTRAINT fk_pk_epizod_elementy_episode
        FOREIGN KEY (epizod_id) REFERENCES pk_epizody(epizod_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_pk_epizod_elementy_pathway_element
        FOREIGN KEY (sciezka_element_id)
        REFERENCES pk_sciezka_elementy(element_id),
    CONSTRAINT fk_pk_epizod_elementy_block
        FOREIGN KEY (klocek_id) REFERENCES pk_klocki(klocek_id),
    CONSTRAINT fk_pk_epizod_elementy_source
        FOREIGN KEY (element_zrodlowy_id)
        REFERENCES pk_epizod_elementy(epizod_element_id),
    CONSTRAINT fk_pk_epizod_elementy_time_unit
        FOREIGN KEY (jednostka_czasu_id)
        REFERENCES pk_jednostki_czasu(jednostka_czasu_id),
    CONSTRAINT fk_pk_epizod_elementy_deadline_base
        FOREIGN KEY (termin_od_epizod_element_id)
        REFERENCES pk_epizod_elementy(epizod_element_id),
    CONSTRAINT ck_pk_epizod_elementy_required
        CHECK (czy_wymagany IN (0, 1)),
    CONSTRAINT ck_pk_epizod_elementy_order_required
        CHECK (czy_wymaga_zlecenia IN (0, 1)),
    CONSTRAINT ck_pk_epizod_elementy_active
        CHECK (czy_aktywny IN (0, 1)),
    CONSTRAINT ck_pk_epizod_elementy_origin
        CHECK (
            typ_pochodzenia IN (
                'SCIEZKA',
                'POWIELENIE',
                'POWIELENIE_AUTOMATYCZNE',
                'RECZNIE'
            )
        ),
    CONSTRAINT ck_pk_epizod_elementy_counts
        CHECK (
            min_liczba IS NULL
            OR max_liczba IS NULL
            OR min_liczba <= max_liczba
        )
);

CREATE TABLE IF NOT EXISTS pk_epizod_elementy_historia (
    historia_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    epizod_element_id bigint NOT NULL,
    epizod_id bigint NOT NULL,
    operacja text NOT NULL,
    dane_przed text,
    dane_po text,
    powod text,
    changed_at timestamptz NOT NULL DEFAULT now(),
    changed_by text,
    CONSTRAINT fk_pk_epizod_elementy_hist_element
        FOREIGN KEY (epizod_element_id)
        REFERENCES pk_epizod_elementy(epizod_element_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_pk_epizod_elementy_hist_episode
        FOREIGN KEY (epizod_id) REFERENCES pk_epizody(epizod_id)
        ON DELETE CASCADE,
    CONSTRAINT ck_pk_epizod_elementy_hist_operation
        CHECK (
            operacja IN (
                'UTWORZENIE',
                'POWIELENIE',
                'POWIELENIE_AUTOMATYCZNE',
                'DEZAKTYWACJA',
                'REAKTYWACJA',
                'EDYCJA'
            )
        )
);

CREATE TABLE IF NOT EXISTS pk_zadania (
    zadanie_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    epizod_id bigint NOT NULL,
    element_id bigint,
    epizod_element_id bigint,
    status text NOT NULL DEFAULT 'DO_ZAPLANOWANIA',
    data_wymagana_do date,
    data_zaplanowana timestamptz,
    data_realizacji timestamptz,
    zrodlo text NOT NULL DEFAULT 'PROGRAM',
    eskulap_system text,
    eskulap_id text,
    eskulap_pracownik text,
    eskulap_data_wizyty timestamptz,
    eskulap_rodzaj_wizyty text,
    eskulap_decyzja text,
    uwagi text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz,
    CONSTRAINT fk_pk_zadania_episode
        FOREIGN KEY (epizod_id) REFERENCES pk_epizody(epizod_id),
    CONSTRAINT fk_pk_zadania_element
        FOREIGN KEY (element_id) REFERENCES pk_sciezka_elementy(element_id)
        ,
    CONSTRAINT fk_pk_zadania_episode_element
        FOREIGN KEY (epizod_element_id)
        REFERENCES pk_epizod_elementy(epizod_element_id)
);

ALTER TABLE pk_zadania
ADD COLUMN IF NOT EXISTS epizod_element_id bigint;

ALTER TABLE pk_zadania
ADD COLUMN IF NOT EXISTS eskulap_pracownik text;

ALTER TABLE pk_zadania
ADD COLUMN IF NOT EXISTS eskulap_data_wizyty timestamptz;

ALTER TABLE pk_zadania
ADD COLUMN IF NOT EXISTS eskulap_rodzaj_wizyty text;

ALTER TABLE pk_zadania
ADD COLUMN IF NOT EXISTS eskulap_decyzja text;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_pk_zadania_episode_element'
    ) THEN
        ALTER TABLE pk_zadania
        ADD CONSTRAINT fk_pk_zadania_episode_element
        FOREIGN KEY (epizod_element_id)
        REFERENCES pk_epizod_elementy(epizod_element_id);
    END IF;
END $$;

COMMIT;
