\set ON_ERROR_STOP on

BEGIN;

CREATE TABLE IF NOT EXISTS pk_users (
    user_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login text NOT NULL UNIQUE,
    full_name text NOT NULL,
    password_hash text NOT NULL,
    must_change_password integer NOT NULL DEFAULT 1,
    is_active integer NOT NULL DEFAULT 1,
    failed_login_count integer NOT NULL DEFAULT 0,
    locked_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz,
    CONSTRAINT ck_pk_users_must_change
        CHECK (must_change_password IN (0, 1)),
    CONSTRAINT ck_pk_users_active CHECK (is_active IN (0, 1)),
    CONSTRAINT ck_pk_users_failed_login CHECK (failed_login_count >= 0)
);

CREATE TABLE IF NOT EXISTS pk_roles (
    role_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code text NOT NULL UNIQUE,
    name text NOT NULL
);

CREATE TABLE IF NOT EXISTS pk_user_roles (
    user_id bigint NOT NULL,
    role_id bigint NOT NULL,
    PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_pk_user_roles_user
        FOREIGN KEY (user_id) REFERENCES pk_users(user_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_pk_user_roles_role
        FOREIGN KEY (role_id) REFERENCES pk_roles(role_id)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS pk_user_units (
    user_id bigint NOT NULL,
    jo_id text NOT NULL,
    jo_symbol text,
    jo_nazwa text,
    is_default integer NOT NULL DEFAULT 0,
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id, jo_id),
    CONSTRAINT fk_pk_user_units_user
        FOREIGN KEY (user_id) REFERENCES pk_users(user_id)
        ON DELETE CASCADE,
    CONSTRAINT ck_pk_user_units_default CHECK (is_default IN (0, 1))
);

CREATE TABLE IF NOT EXISTS pk_programy (
    program_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kod text NOT NULL UNIQUE,
    nazwa text NOT NULL,
    wersja text,
    opis text,
    czy_aktywny integer NOT NULL DEFAULT 1,
    data_od date,
    data_do date,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz,
    CONSTRAINT ck_pk_programy_active CHECK (czy_aktywny IN (0, 1))
);

CREATE TABLE IF NOT EXISTS pk_program_units (
    program_id bigint NOT NULL,
    jo_id text NOT NULL,
    jo_symbol text,
    jo_nazwa text,
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (program_id, jo_id),
    CONSTRAINT fk_pk_program_units_program
        FOREIGN KEY (program_id) REFERENCES pk_programy(program_id)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS pk_sciezki (
    sciezka_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    program_id bigint NOT NULL,
    kod text NOT NULL,
    nazwa text NOT NULL,
    opis text,
    czy_aktywna integer NOT NULL DEFAULT 1,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz,
    CONSTRAINT uq_pk_sciezki_program_kod UNIQUE (program_id, kod),
    CONSTRAINT fk_pk_sciezki_program
        FOREIGN KEY (program_id) REFERENCES pk_programy(program_id),
    CONSTRAINT ck_pk_sciezki_active CHECK (czy_aktywna IN (0, 1))
);

CREATE TABLE IF NOT EXISTS pk_pathway_units (
    sciezka_id bigint NOT NULL,
    jo_id text NOT NULL,
    jo_symbol text,
    jo_nazwa text,
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (sciezka_id, jo_id),
    CONSTRAINT fk_pk_pathway_units_pathway
        FOREIGN KEY (sciezka_id) REFERENCES pk_sciezki(sciezka_id)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS pk_typy_elementow (
    typ_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kod text NOT NULL UNIQUE,
    nazwa text NOT NULL
);

CREATE TABLE IF NOT EXISTS pk_klocki (
    klocek_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kod text NOT NULL UNIQUE,
    nazwa text NOT NULL,
    typ text NOT NULL,
    opis text,
    ikona text,
    czy_aktywny integer NOT NULL DEFAULT 1,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz,
    CONSTRAINT ck_pk_klocki_active CHECK (czy_aktywny IN (0, 1))
);

CREATE TABLE IF NOT EXISTS pk_sciezka_elementy (
    element_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sciezka_id bigint NOT NULL,
    klocek_id bigint NOT NULL,
    lp integer NOT NULL,
    nazwa_w_sciezce text NOT NULL,
    min_liczba integer DEFAULT 0,
    max_liczba integer,
    czy_obowiazkowy integer NOT NULL DEFAULT 0,
    czy_wymaga_zlecenia integer NOT NULL DEFAULT 0,
    termin_liczba integer,
    termin_jednostka text,
    termin_od text,
    warunek_aktywacji text,
    opis_organizacyjny text,
    czy_aktywny integer NOT NULL DEFAULT 1,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz,
    CONSTRAINT uq_pk_sciezka_elementy_lp UNIQUE (sciezka_id, lp),
    CONSTRAINT fk_pk_sciezka_elementy_pathway
        FOREIGN KEY (sciezka_id) REFERENCES pk_sciezki(sciezka_id),
    CONSTRAINT fk_pk_sciezka_elementy_block
        FOREIGN KEY (klocek_id) REFERENCES pk_klocki(klocek_id),
    CONSTRAINT ck_pk_sciezka_elementy_required
        CHECK (czy_obowiazkowy IN (0, 1)),
    CONSTRAINT ck_pk_sciezka_elementy_order
        CHECK (czy_wymaga_zlecenia IN (0, 1)),
    CONSTRAINT ck_pk_sciezka_elementy_active
        CHECK (czy_aktywny IN (0, 1)),
    CONSTRAINT ck_pk_sciezka_elementy_counts
        CHECK (
            min_liczba IS NULL
            OR max_liczba IS NULL
            OR min_liczba <= max_liczba
        )
);

CREATE TABLE IF NOT EXISTS pk_sciezka_zaleznosci (
    zaleznosc_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sciezka_id bigint NOT NULL,
    element_od_id bigint NOT NULL,
    element_do_id bigint NOT NULL,
    typ text NOT NULL,
    opis text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz,
    CONSTRAINT uq_pk_sciezka_zaleznosci
        UNIQUE (sciezka_id, element_od_id, element_do_id),
    CONSTRAINT fk_pk_sciezka_zaleznosci_pathway
        FOREIGN KEY (sciezka_id) REFERENCES pk_sciezki(sciezka_id),
    CONSTRAINT fk_pk_sciezka_zaleznosci_from
        FOREIGN KEY (element_od_id)
        REFERENCES pk_sciezka_elementy(element_id),
    CONSTRAINT fk_pk_sciezka_zaleznosci_to
        FOREIGN KEY (element_do_id)
        REFERENCES pk_sciezka_elementy(element_id),
    CONSTRAINT ck_pk_sciezka_zaleznosci_type
        CHECK (typ IN ('KOLEJNOSC', 'WARUNEK')),
    CONSTRAINT ck_pk_sciezka_zaleznosci_self
        CHECK (element_od_id <> element_do_id)
);

CREATE TABLE IF NOT EXISTS pk_wyzwalacze (
    trigger_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    element_id bigint NOT NULL,
    trigger_type text NOT NULL,
    trigger_element_id bigint,
    opis text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz,
    CONSTRAINT fk_pk_wyzwalacze_element
        FOREIGN KEY (element_id) REFERENCES pk_sciezka_elementy(element_id),
    CONSTRAINT fk_pk_wyzwalacze_source
        FOREIGN KEY (trigger_element_id)
        REFERENCES pk_sciezka_elementy(element_id),
    CONSTRAINT ck_pk_wyzwalacze_type CHECK (
        trigger_type IN (
            'START_EPIZODU',
            'PO_ZAKONCZENIU',
            'PO_ZLECENIU',
            'PO_WYNIKU',
            'RECZNIE'
        )
    )
);

CREATE TABLE IF NOT EXISTS pk_epizody (
    epizod_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pacjent_id text NOT NULL,
    program_id bigint,
    sciezka_id bigint,
    data_start date,
    data_zakonczenia date,
    status text NOT NULL DEFAULT 'NOWY',
    koordynator_id text,
    uwagi text,
    source_system text,
    source_type text,
    source_id text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz,
    CONSTRAINT fk_pk_epizody_program
        FOREIGN KEY (program_id) REFERENCES pk_programy(program_id),
    CONSTRAINT fk_pk_epizody_pathway
        FOREIGN KEY (sciezka_id) REFERENCES pk_sciezki(sciezka_id)
);

CREATE TABLE IF NOT EXISTS pk_zadania (
    zadanie_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    epizod_id bigint NOT NULL,
    element_id bigint,
    status text NOT NULL DEFAULT 'DO_ZAPLANOWANIA',
    data_wymagana_do date,
    data_zaplanowana timestamptz,
    data_realizacji timestamptz,
    zrodlo text NOT NULL DEFAULT 'PROGRAM',
    eskulap_system text,
    eskulap_id text,
    uwagi text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz,
    CONSTRAINT fk_pk_zadania_episode
        FOREIGN KEY (epizod_id) REFERENCES pk_epizody(epizod_id),
    CONSTRAINT fk_pk_zadania_element
        FOREIGN KEY (element_id) REFERENCES pk_sciezka_elementy(element_id)
);

CREATE TABLE IF NOT EXISTS pk_patient_cache (
    patient_cache_id bigserial PRIMARY KEY,
    pacjent_id_eskulap text NOT NULL UNIQUE,
    pesel_enc bytea,
    imie_enc bytea,
    nazwisko_enc bytea,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz
);

CREATE OR REPLACE FUNCTION kompas_encrypt_patient_text(value text)
RETURNS bytea
LANGUAGE plpgsql
SECURITY INVOKER
AS $$
DECLARE
    data_key text;
BEGIN
    IF value IS NULL THEN
        RETURN NULL;
    END IF;
    data_key := NULLIF(current_setting('kompas.data_key', true), '');
    IF data_key IS NULL THEN
        RAISE EXCEPTION
            'Brak klucza sesji kompas.data_key'
            USING ERRCODE = '22023';
    END IF;
    RETURN pgp_sym_encrypt(value, data_key, 'cipher-algo=aes256');
END;
$$;

CREATE OR REPLACE FUNCTION kompas_decrypt_patient_text(value bytea)
RETURNS text
LANGUAGE plpgsql
SECURITY INVOKER
AS $$
DECLARE
    data_key text;
BEGIN
    IF value IS NULL THEN
        RETURN NULL;
    END IF;
    data_key := NULLIF(current_setting('kompas.data_key', true), '');
    IF data_key IS NULL THEN
        RAISE EXCEPTION
            'Brak klucza sesji kompas.data_key'
            USING ERRCODE = '22023';
    END IF;
    RETURN pgp_sym_decrypt(value, data_key);
END;
$$;

COMMIT;
